<a href="https://colab.research.google.com/github/er-jyotigoel/PGP-AIML-ONLINE-JANUARY-24A/blob/Module1-Introduction-to-Python/Self_Study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
vec1 = np.arange(0, 12)
vec2 = vec1.reshape(4, 3)
print(vec2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [4]:
vec1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
vec2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [7]:
newarr = arr.reshape(3, 5)
newarr

ValueError: cannot reshape array of size 12 into shape (3,5)

In [8]:
newarr = arr.reshape(5, 3)

ValueError: cannot reshape array of size 12 into shape (5,3)

In [9]:
newarr = arr.shape(3, 5)
newarr

TypeError: 'tuple' object is not callable

In [10]:
np.log10( )

TypeError: log10() takes from 1 to 2 positional arguments but 0 were given

In [11]:
np.log()

TypeError: log() takes from 1 to 2 positional arguments but 0 were given

In [12]:
np.log_base(10)

AttributeError: module 'numpy' has no attribute 'log_base'

In [13]:
np.log(exp(10))

NameError: name 'exp' is not defined

In [14]:
np.log()

TypeError: log() takes from 1 to 2 positional arguments but 0 were given

In [15]:
np.log10( )

TypeError: log10() takes from 1 to 2 positional arguments but 0 were given

In [16]:
np.log10(2)

0.3010299956639812

In [17]:
mat = np.array([[1,2,3,4],[5,6,7,8]])

In [18]:
mat

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
mat.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [20]:
mat.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [21]:
mat.transpose(4,2)

AxisError: axis 4 is out of bounds for array of dimension 2

In [22]:
mat.transpose(2,4)

AxisError: axis 2 is out of bounds for array of dimension 2

In [23]:
np.random.randint(100)

80

In [24]:
np.random.rand(100)

array([0.04697893, 0.79334066, 0.70346936, 0.39413815, 0.91444177,
       0.05723817, 0.84377898, 0.90869145, 0.92839486, 0.32716272,
       0.42927835, 0.63719591, 0.25305482, 0.11017413, 0.98630329,
       0.84372787, 0.22840536, 0.35837099, 0.83281489, 0.39584565,
       0.16613816, 0.338284  , 0.37880067, 0.52912614, 0.87060906,
       0.67140722, 0.924112  , 0.23824719, 0.25142593, 0.65971588,
       0.71093502, 0.66344128, 0.85727975, 0.63154926, 0.99135582,
       0.09116494, 0.2123474 , 0.09453825, 0.89106603, 0.80274945,
       0.56944473, 0.9016549 , 0.31231523, 0.53900856, 0.7372404 ,
       0.95356666, 0.24647978, 0.41380772, 0.38195669, 0.33997205,
       0.91744566, 0.52512558, 0.0713513 , 0.31958034, 0.79555614,
       0.51659084, 0.39948245, 0.58597541, 0.52220974, 0.27959756,
       0.83661618, 0.56944425, 0.77817998, 0.27519164, 0.4518484 ,
       0.80562812, 0.44979541, 0.13943561, 0.81444188, 0.36403324,
       0.1935681 , 0.75617092, 0.61875357, 0.48468764, 0.32663

In [25]:
mat = np.array([[1,2,3,4,5], [6,7,8,9,10]])
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [26]:
mat[2,3]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [27]:
mat[0,3]

4

In [28]:
mat[1,2]

8

In [29]:
test_mat_1 = np.array([[1,2],[3,4],[5,6]])
test_mat_2 = test_mat_1
test_mat_2[1,0] = 2
test_mat_1[2,0] = 4
print(test_mat_1)

[[1 2]
 [2 4]
 [4 6]]


In [30]:
test_array = np.array([10, 115, 172, 15, 147,13])
test_array[test_array>0] = 30
print(test_array)

[30 30 30 30 30 30]


In [31]:
vec = np.array([4,7,8,9,10,6,1])
print(vec[vec>6])

[ 7  8  9 10]


In [32]:
s = pd.Series([5,5,5,5], index=[0, 1, 2, 3])
print(s)

0    5
1    5
2    5
3    5
dtype: int64


In [33]:
series = pd.Series([11,22,33,44], index=[0, 1, 2, 3])
mult_series = series*20
print(mult_series)

0    220
1    440
2    660
3    880
dtype: int64


In [34]:
df = pd.DataFrame({'Name': ['Tom', 'Joseph', 'Krish', 'John'], 'Age': [20, 21, 19, 18]} )

In [35]:
df

Name  Age
0     Tom   20
1  Joseph   21
2   Krish   19
3    John   18

In [36]:
test_array = [10, 11.5, 12, 13.5, 14,15]

In [37]:
test_array[2:3]

[12]

In [ ]:
list_l =[[12,34,55,],[66,45,77],[45,77,88]]
np.array(list_l)

array([[12, 34, 55],
       [66, 45, 77],
       [45, 77, 88]])

In [ ]:
score = [10, 15, 20, 25]
pd.Series(data=score, index = ['a','b','c','d'])

a    10
b    15
c    20
d    25
dtype: int64

In [ ]:
np.arange(0,22,6)

array([ 0,  6, 12, 18])

In [ ]:
demo_array = np.arange(10,21)
subset_demo_array = demo_array[0:7]
subset_demo_array[:]= 101
subset_demo_array

array([101, 101, 101, 101, 101, 101, 101])

In [ ]:
flowers = pd.Series([2, 3, 5, 4], index=['lily', 'rose', 'daisy', 'lotus'])
flowers['daisy']
flowers[0]
flowers[0]
flowers[:'daisy']

lily     2
rose     3
daisy    5
dtype: int64

In [ ]:
s1 = pd.Series(['a', 'b'])
s2 = pd.Series(['c', 'd'])

In [ ]:
pd.concat([s1, s2])
s1[0]

'a'

In [ ]:
pd.concat([s1+ s2])

0    ac
1    bd
dtype: object

In [ ]:
pd.concat(s1, s2)

/var/folders/wf/04wfhfsj657dzn9ll_st2w2h0000gn/T/ipykernel_12057/4253961264.py:1: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only.
  pd.concat(s1, s2)


TypeError: first argument must be an iterable of pandas objects, you passed an object of type "Series"

In [ ]:
pd.concat[s1, s2]

TypeError: 'function' object is not subscriptable

In [ ]:
list_ = [4]
abc =np.array(list_)
abc

array([4])

In [ ]:
np.array[‘list_’]

SyntaxError: invalid character '‘' (U+2018) (1844531553.py, line 1)

In [ ]:
np.array[list_]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [ ]:
np.array{list_}

SyntaxError: invalid syntax (4135652410.py, line 1)

In [ ]:
football = [24, 235, 34, 456, 65, 67]
football

[24, 235, 34, 456, 65, 67]

In [ ]:
n6 = np.matrix([[ 1, 4, 9, 121, 144, 169],
[ 16, 25, 36, 196, 225, 256], [ 49, 64, 81, 289, 324, 361]])

In [ ]:
n6p = np.arange(20)

matrix([[  1,   4,   9, 121, 144, 169],
        [ 16,  25,  36, 196, 225, 256],
        [ 49,  64,  81, 289, 324, 361]])

In [ ]:
n6.mean()

131.66666666666666

In [ ]:
n1 = np.matrix([[121, 144, 169],
[196, 225, 256], [ 289, 324, 361]])
n2 = np.matrix([[ 1, 4, 9],
[ 1, 5, 4], [ 9, 4, 8]])

In [ ]:
np.dot(n1,n2)

matrix([[1786, 1880, 3017],
        [2725, 2933, 4712],
        [3862, 4220, 6785]])

In [ ]:
np.arange(20)[2:7]

array([2, 3, 4, 5, 6])

In [ ]:
np.arange(20)[0::9]

array([ 0,  9, 18])

In [ ]:
p = np.arange(20)

In [ ]:
p

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
p[:-1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [ ]:
p[-1]

19

In [ ]:
p[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [ ]:
np.matrix([[ 1, 4, 9], [ 1, 5, 4], [ 9, 4, 8]])[::-1]

matrix([[9, 4, 8],
        [1, 5, 4],
        [1, 4, 9]])

In [ ]:
df = pd.read_csv('Practice quiz- Week 1/books.csv')

In [ ]:
df.describe()

average_rating        isbn13    num_pages  ratings_count  \
count     5000.000000  5.000000e+03  4967.000000   5.000000e+03   
mean         3.931932  9.752758e+12   341.094021   2.017549e+04   
std          0.348741  5.129254e+11   230.986115   1.175026e+05   
min          0.000000  8.987060e+09     1.000000   0.000000e+00   
25%          3.770000  9.780345e+12   200.000000   1.050000e+02   
50%          3.960000  9.780571e+12   304.000000   7.915000e+02   
75%          4.140000  9.780871e+12   416.500000   5.348750e+03   
max          5.000000  9.789879e+12  3342.000000   2.457092e+06   

       text_reviews_count         year  
count         5000.000000  5000.000000  
mean           592.688600  2000.131800  
std           2539.539004     8.069043  
min              0.000000  1913.000000  
25%              9.000000  1998.000000  
50%             49.000000  2003.000000  
75%            249.000000  2005.000000  
max          55843.000000  2019.000000

In [ ]:
df.null()

AttributeError: 'DataFrame' object has no attribute 'null'

In [ ]:
df.isnull().sum()

title                  0
author                 0
average_rating         0
isbn13                 0
language_code         77
num_pages             33
ratings_count          0
text_reviews_count     0
publisher              0
year                   0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   title               5000 non-null   object 
 1   author              5000 non-null   object 
 2   average_rating      5000 non-null   float64
 3   isbn13              5000 non-null   int64  
 4   language_code       4923 non-null   object 
 5   num_pages           4967 non-null   float64
 6   ratings_count       5000 non-null   int64  
 7   text_reviews_count  5000 non-null   int64  
 8   publisher           5000 non-null   object 
 9   year                5000 non-null   int64  
dtypes: float64(2), int64(4), object(4)
memory usage: 390.8+ KB


In [ ]:
len(pd.unique(df['publisher']))

1408

In [ ]:
df[df['average_rating']>4]

title  \
1     La Cucina Di Lidia: Recipes and Memories from ...   
4     The Killing Dance (Anita Blake  Vampire Hunter...   
5          The Hand of Chaos (The Death Gate Cycle  #5)   
6                                       On Intelligence   
11                        Merlin's Tour of the Universe   
...                                                 ...   
4991                                       'Salem's Lot   
4992                  A Mad People's History of Madness   
4993     A Christmas Carol (Great Illustrated Classics)   
4995                                 The Complete Works   
4999  The Avignon Quintet: Monsieur  Livia  Constanc...   

                           author  average_rating         isbn13  \
1     Lidia Matticchio Bastianich            4.14  9780767914222   
4             Laurell K. Hamilton            4.13  9780425209066   
5                   Margaret Weis            4.06  9780553563696   
6                    Jeff Hawkins            4.12  9780805078534   
11            Neil deGrasse Tyson            4.02  9780385488358   
...                           ...             ...            ...   
4991                 Stephen King            4.02  9780965772419   
4992                Dale Peterson            4.33  9780822953319   
4993             Malvina G. Vogel            4.36  9781596792371   
4995          Michel de Montaigne            4.44  9781400040216   
4999             Lawrence Durrell            4.07  9780571225552   

     language_code  num_pages  ratings_count  text_reviews_count  \
1            en-GB      288.0             48                   3   
4            en-US      368.0          59524                 946   
5              eng      446.0          16301                 117   
6              eng      261.0           5347                 396   
11             eng      318.0            305                  27   
...            ...        ...            ...                 ...   
4991           eng      405.0           1039                 130   
4992           eng      384.0              9                   0   
4993           eng      238.0            466                  31   
4995           eng     1392.0            166                  13   
4999         en-US     1376.0            287                  23   

                           publisher  year  
1                    Clarkson Potter  2003  
4                  Berkley Hardcover  2006  
5                            Spectra  1993  
6               St. Martin's Griffin  2005  
11                 Main Street Books  1997  
...                              ...   ...  
4991                       Doubleday  1975  
4992  University of Pittsburgh Press  1982  
4993         Abdo Publishing Company  2005  
4995              Everyman's Library  2003  
4999                   Faber & Faber  2004  

[2115 rows x 10 columns]

In [ ]:
df[df['language_code'].isnull()]

title  \
61                          Black Hole  tome 3: Visions   
63                                             鋼之鍊金術師 9   
108                              La Maison des feuilles   
161   Jojo's Bizarre Adventure  Tome 14: Le Navire d...   
172                                       O Historiador   
...                                                 ...   
4656                                          Galápagos   
4742  Kenang-Kenangan Seorang Geisha (Memoirs of a G...   
4744                                         魔戒首部曲：魔戒現身   
4790                                    Le Petit Prince   
4791                                      Trainspotting   

                        author  average_rating         isbn13 language_code  \
61               Charles Burns            4.00  9782840555520           NaN   
63              Hiromu Arakawa            4.57  9789861156521           NaN   
108        Mark Z. Danielewski            4.10  9782207252000           NaN   
161             Hirohiko Araki            4.41  9782290328057           NaN   
172          Elizabeth Kostova            3.78  9788573027105           NaN   
...                        ...             ...            ...           ...   
4656         Kurt Vonnegut Jr.            3.88  9782246371922           NaN   
4742             Arthur Golden            4.11  9789833346684           NaN   
4744            J.R.R. Tolkien            4.36  9789570823363           NaN   
4790  Antoine de Saint-Exupéry            4.31  9780156013987           NaN   
4791              Irvine Welsh            4.09  9782020336468           NaN   

      num_pages  ratings_count  text_reviews_count  \
61         63.0              3                   0   
63        184.0              4                   0   
108       978.0             79                  13   
161       189.0              4                   2   
172       544.0             43                   3   
...         ...            ...                 ...   
4656      282.0             27                   1   
4742      784.0             28                   6   
4744      608.0             26                   0   
4790       87.0           3045                 215   
4791      344.0          59077                 857   

                        publisher  year  
61                       Delcourt  2001  
63                             東立  2004  
108                        Denoël  2002  
161                       J'ai lu  2003  
172    Suma de Letras Brasileiras  2005  
...                           ...   ...  
4656                      Grasset  1994  
4742  Marshall Cavendish Editions  2006  
4744                 聯經出版事業股份有限公司  2001  
4790                Mariner Books  2001  
4791                        Seuil  1998  

[77 rows x 10 columns]

In [ ]:
df[df['language_code'] == '']

Empty DataFrame
Columns: [title, author, average_rating, isbn13, language_code, num_pages, ratings_count, text_reviews_count, publisher, year]
Index: []

In [ ]:
df[df['language_code'] == 'NaN']

Empty DataFrame
Columns: [title, author, average_rating, isbn13, language_code, num_pages, ratings_count, text_reviews_count, publisher, year]
Index: []

In [ ]:
df[df['language_code'] == np.nan]

Empty DataFrame
Columns: [title, author, average_rating, isbn13, language_code, num_pages, ratings_count, text_reviews_count, publisher, year]
Index: []

In [ ]:
df(df['average_rating']>4.5) and (df['ratings_count']< 10)

TypeError: 'DataFrame' object is not callable

In [ ]:
df[(df['average_rating']>4.5) & (df['ratings_count']< 10)]

title  \
63                                             鋼之鍊金術師 9   
178                                            鋼之鍊金術師 6   
224                             Stargirl LitPlans on CD   
454   Literature Circle Guide: Bridge to Terabithia:...   
584                       Falling Angels (Luc Actar #1)   
681        Fanning the Flame: Bible  Cross  and Mission   
696                  Tyrannosaurus Wrecks (Stanley  #1)   
741   The John Deere Two-Cylinder Tractor Encycloped...   
757   The American Campaign: U.S. Presidential Campa...   
1837  The Goon Show  Volume 4: My Knees Have Fallen ...   
1856                                          鋼之鍊金術師 10   
1960  Wissenschaft der Logik: Die Lehre Vom Begriff ...   
2244  Getting a Grip on the Basics: Building a Firm ...   
2496                               Come Away My Beloved   
3178  Organizational Architecture: Designs for Chang...   
3438         Bill Gates: Computer Legend (Famous Lives)   
3706  A Wife After God's Own Heart Growth and Study ...   
3833  His Princess Devotional: A Royal Encounter Wit...   
3909                 Little Big Book for God's Children   
3927  Colossians and Philemon: A Critical and Exeget...   
4108                  Willem de Kooning: Late Paintings   
4415                                           Corvette   
4455  The Complete Theory Fun Factory: Music Theory ...   
4917                          Taxation of Mineral Rents   
4933  Oliver Wendell Holmes in Paris: Medicine  Theo...   

                             author  average_rating         isbn13  \
63                   Hiromu Arakawa            4.57  9789861156521   
178                  Hiromu Arakawa            4.58  9789861146140   
224                 Mary B. Collins            4.86  9781583372920   
454                  Tara MacCarthy            5.00  9780439271714   
584               Melissa M. Garcia            4.67  9780595377107   
681                  Chris    Green            5.00  9780310249870   
696                  Laura Driscoll            5.00  9780786845033   
741                   Don Macmillan            4.75  9780760329634   
757               James E. Campbell            5.00  9780890969403   
1837                     NOT A BOOK            5.00  9780563388692   
1856                 Hiromu Arakawa            4.60  9789861156538   
1960  Georg Wilhelm Friedrich Hegel            4.78  9783787307678   
2244                  Beth A. Jones            4.67  9781577948261   
2496             Frances J. Roberts            4.58  9781593109158   
3178                David A. Nadler            4.62  9781555424435   
3438               Sara Barton-Wood            5.00  9780739844328   
3706               Elizabeth George            4.69  9780736911689   
3833            Sheri Rose Shepherd            5.00  9781590529621   
3909                     Alice Wong            4.88  9780941807555   
3927                 R. McL. Wilson            5.00  9780567044716   
4108                Julie Sylvester            5.00  9783829602266   
4415                   Jerry Burton            4.83  9780883631218   
4455              Ian        Martin            5.00  9780851621814   
4917                   Ross Garnaut            5.00  9780198284543   
4933             William C. Dowling            5.00  9781584655800   

     language_code  num_pages  ratings_count  text_reviews_count  \
63             NaN      184.0              4                   0   
178            NaN      191.0              5                   0   
224            eng      210.0              5                   0   
454            eng       32.0              4                   1   
584            eng      216.0              1                   0   
681            eng      336.0              1                   1   
696            eng       24.0              2                   1   
741            eng      256.0              4                   0   
757            eng      314.0              0                   0   
1837          

In [ ]:
df(df[average_rating]>4.5) && (df[ratings_count]< 10)

SyntaxError: invalid syntax (1391869336.py, line 1)

In [ ]:
df[(df['average_rating']>=4.5) or (df['ratings_count']<= 10)]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
mean_rating_eng = df.groupby('language_code')['average_rating'].mean()

In [ ]:
mean_rating_eng

language_code
en-GB    3.922523
en-US    3.914800
eng      3.931143
ger      3.979773
grc      2.366667
jpn      4.252381
lat      4.170000
mul      4.116000
spa      3.927938
Name: average_rating, dtype: float64

In [ ]:
mean_rating_eng['eng']

3.931142857142857

In [ ]:
df.iloc[1:5,1:4]

author  average_rating         isbn13
1  Lidia Matticchio Bastianich            4.14  9780767914222
2             James Scott Bell            4.00  9780310243878
3         David Foster Wallace            3.86  9780349111889
4          Laurell K. Hamilton            4.13  9780425209066

In [ ]:
df.iloc[0:5,0:4]

title  \
0                        The Hunchback of Notre-Dame   
1  La Cucina Di Lidia: Recipes and Memories from ...   
2                                  Breach of Promise   
3                  Brief Interviews with Hideous Men   
4  The Killing Dance (Anita Blake  Vampire Hunter...   

                        author  average_rating         isbn13  
0                  Victor Hugo            4.00  9780345472427  
1  Lidia Matticchio Bastianich            4.14  9780767914222  
2             James Scott Bell            4.00  9780310243878  
3         David Foster Wallace            3.86  9780349111889  
4          Laurell K. Hamilton            4.13  9780425209066

In [ ]:
df.iloc[1:5,0:4]

title  \
1  La Cucina Di Lidia: Recipes and Memories from ...   
2                                  Breach of Promise   
3                  Brief Interviews with Hideous Men   
4  The Killing Dance (Anita Blake  Vampire Hunter...   

                        author  average_rating         isbn13  
1  Lidia Matticchio Bastianich            4.14  9780767914222  
2             James Scott Bell            4.00  9780310243878  
3         David Foster Wallace            3.86  9780349111889  
4          Laurell K. Hamilton            4.13  9780425209066

In [ ]:
df.iloc[0:5,1:4]

author  average_rating         isbn13
0                  Victor Hugo            4.00  9780345472427
1  Lidia Matticchio Bastianich            4.14  9780767914222
2             James Scott Bell            4.00  9780310243878
3         David Foster Wallace            3.86  9780349111889
4          Laurell K. Hamilton            4.13  9780425209066

In [ ]:
books_2010 = df[df['year'] == 2010]
books_2010

title  \
40    The Walking Dead  Book One (The Walking Dead #...   
359        Things: A Story of the Sixties; A Man Asleep   
425   The Gap Into Vision: Forbidden Knowledge (Gap ...   
985                                     Never Let Me Go   
1696           The Unexpected Guest: A Play In Two Acts   
1789  A Short History of Nearly Everything (Illustra...   
2620                                         The Client   
2695                                      Lord of Light   
2706         Pimsleur German Level 1 CD: [Lessons 1-30]   
3079                             Tim Burton: Interviews   
3724                                     Less Than Zero   
4460                                     Riddley Walker   
4650  The Beatles' Story on Capitol Records  Part Tw...   
4891   Judy Moody Declares Independence (Judy Moody #6)   
4914  Earthquake in the Early Morning (Magic Tree Ho...   

                          author  average_rating         isbn13 language_code  \
40                Robert Kirkman            4.35  9781582406190           eng   
359                Georges Perec            3.98  9781567921571           eng   
425         Stephen R. Donaldson            3.99  9780553297607         en-US   
985               Kazuo Ishiguro            3.82  9781400078776           eng   
1696             Agatha Christie            3.83  9780573014673           eng   
1789                 Bill Bryson            4.21  9780385663557           eng   
2620                John Grisham            4.00  9780385339087           eng   
2695               Roger Zelazny            4.10  9780060567231           eng   
2706  Pimsleur Language Programs            4.23  9780743518369           eng   
3079              Kristian Fraga            4.26  9781578067596           eng   
3724           Bret Easton Ellis            3.58  9780679781493           eng   
4460               Russell Hoban            4.03  9780747559047           eng   
4650                Bruce Spizer            4.72  9780966264920           eng   
4891              Megan McDonald            4.08  9780763628000           eng   
4914           Mary Pope Osborne            3.94  9780679890706           eng   

      num_pages  ratings_count  text_reviews_count  \
40        304.0          34751                1346   
359       221.0           1062                  63   
425       480.0           5020                 101   
985       288.0         380646               22957   
1696      100.0           2813                 167   
1789      624.0             28                   7   
2620      483.0         367399                1978   
2695      296.0          23392                1104   
2706       16.0             58                  10   
3079      192.0            103                   7   
3724      208.0          55900                2543   
4460      236.0            305                  44   
4650      264.0             29                   0   
4891      160.0           3884                 132   
4914       96.0           6816                 227   

                            publisher  year  
40                       Image Comics  2010  
359         David R. Godine Publisher  2010  
425                            Bantam  2010  
985                     Vintage Books  2010  
1696                Samuel French Ltd  2010  
1789                    Anchor Canada  2010  
2620                            Delta  2010  
2695                   Harper Voyager  2010  
2706                         Pimsleur  2010  
3079  University Press of Mississippi  2010  
3724                    Vintage Books  2010  
4460                       Bloomsbury  2010  
4650    Four Ninety-Eight Productions  2010  
4891                       Candlewick  2010  
4914   Random House for Young Readers  2010

In [ ]:
len(books_2010)

15